//
// Created by Tungsten on 2022/9/4.
//

#ifndef HELLO_MINECRAFT_LAUNCHER_POCKET_EDITION_LOADME_H
#define HELLO_MINECRAFT_LAUNCHER_POCKET_EDITION_LOADME_H

void* setup_dl_hook(void);

#endif //HELLO_MINECRAFT_LAUNCHER_POCKET_EDITION_LOADME_H
