name: Debug Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Print environment variables
      run: |
        echo "GitHub repository: $GITHUB_REPOSITORY"
        echo "GitHub ref: $GITHUB_REF"
        echo "GitHub event name: $GITHUB_EVENT_NAME"
        echo "GitHub actor: $GITHUB_ACTOR"

    - name: List files in the repository
      run: ls -la

    - name: Build with Gradle
      run: ./gradlew build
